### ISSUE TITLE
How do I make it move along the X or Z axis?

### ISSUE THREAD

**Issue by diegobona** [boytchev/mannequin.js#22]
I only see this. Why are there no MovX and MovZ?
```
if (cbMovY.checked)
   inverseKinematics(joint, '', step);
```

**Comment by boytchev** [comment]
Hi –

There are historical reasons for this. The main application of mannequin.js is in one of my courses, where a group of mannequins are controlled with JavaScript – this includes motions along all axes. So, in JavaScript you can move the body in any direction. This is an example: [qa-motion-in-xyz.html](https://boytchev.github.io/mannequin.js/examples/qa-motion-in-xyz.html).

The editor, on the other hand, is just a supplementary module for building postures, and it is not intended for building scenes. The editor has a vertical motion only to move the figure up/down to touch the ground (instead of calculating the vertical offset in JavaScript). 

So, the editor has no horizontal motion (i.e. X and Z directions) because I have never needed such motion in the editor. Such motion might be needed when I implement support for multiple figures. 

– Pavel

PS. If you want to move the figure horizontally because some body part is out of the screen and you cannot access it, you can pan the figure with the right mouse button.

**Comment by diegobona** [comment]
Well, thank you very much. When can multiple figures be added to the scene be implemented?

**Comment by boytchev** [comment]
Hi –

There is no specific time schedule. Currently I'm focused on two other projects: [Suica](https://boytchev.github.io/suica/) and [Suica SCORM](https://boytchev.github.io/scorm/) as I will need them both for the academic year starting this October. So, I might have a look at mannequin.js after I finish Suica.

In any case, multiple body support is planned, it is added in my todo list in December 2021 ( see #18 )

– Pavel

**Comment by boytchev** [comment]
Hi –

Just uploaded a new version. The posture editor now supports multiple bodies, as well as moving along X, Y and Z. 

– Pavel
