### ISSUE TITLE
Export 3D Model to GLTF or GLB

### ISSUE THREAD

**Issue by ksachikonye** [boytchev/mannequin.js#25]
I really like your tool and see so much potential in it. I am using it in a personal project. Say I wanted to use the models generated on an actual 3D map or a track (using Mapbox or Googlemaps), how can I best export them ? I am a beginner in both javascript and web development and would welcome any suggestions.  It took me quite a while to figure out how to run mannequin.js from a script imported by the index.html and to figure out how to change the dimensions of the page in order for the 3D canvas to appear as part of a larger scientific analysis softeware. Currently, I made a large set of postures using posture-editor and can now include that as part of a webpage. An animated posture in mannequin.js canvas will not convey as much info as an animated posture embedded in mapbox or any other three.js web-gl service.

 I saw a question from someone asking you of the use of your app :) I found that crazy. Those people who need your app will, through search engines, end up at mannequin.js, its a solution and if you dont have a problem that can be solved by mannequin.js, you would struggle finding its versatility.

**Comment by boytchev** [comment]
Hi -

In the best case situation, if Mapbox/GoogleMaps allow custom JS code **and** if their graphics is based on Three.js, then you should be able to draw and animate mannequin figures directly.

If any of the above two conditions is not met, but Mapbox/GoogleMaps allow adding GLTF models, then there is a chance, although it is not that straightforward:

- Create a small page with the figure (its posture can be taken from the editor).
- Add code to export the figure to GLTF or GLB. This should be possible, because the figure is a group of Three.js objects and because Three.js has exporter to GLTF.
- Then you can import the created model in Mapbox/GoogleMaps.

If the figure has some animation, that you want to store in the GLTF, then you should first represent this animation in a way that GLTF can process.

So, the bottom line is:

- Creating GLTF/GLB with static posture requires some programming, but it is relatively easy (I have exported Three.js objects to GLB in the past, but I have never done it with mannequin figures, however, I expect that it is easy to do)
- Creating GLTF/GLB with animated posture requires a lot more programming, and might not be easy (I have never created GLTF-friendly animations, so I'm not sure how difficult it is to create them)

- Pavel

**Comment by boytchev** [comment]
Ksachikonye –

Some good news and some bad news.

- The good news: I gave it a try and created a method `exportGLTF`, so once you have a non-animated posture, you can export it to GLTF or its binary format. I tried to import it in Blender and in Paint3D and it works fine. See attached snapshots.
- The bad news: until December 24 I will refrain from modifying the mannequin.js on GitHub, as it is currently used by my students for a homework assignment. If there are several versions of mannequin, it may confuse some of them. Could you wait till then? If not, we can find another way to send you the files.

Attached is the produced GLB file (zipped), so you can try it with your map software.

![image](https://user-images.githubusercontent.com/70705048/205491982-de994ac4-dd5b-4dff-ade5-88e0f881fcd9.png)
![image](https://user-images.githubusercontent.com/70705048/205492013-6dcb8de3-f122-454d-acee-f80273e58710.png)
[mannequin_posture.zip](https://github.com/boytchev/mannequin.js/files/10148549/mannequin_posture.zip)

– Pavel

**Comment by ksachikonye** [comment]
Thanks for the detailed reply. I would then ask the following if you do not mind:

I am making a tool for sprint running simulations. I have accurate detailed information (from smart running suit, watches, shoes etc) and medical information (genome, microbiome), clinical blood tests etc. The application shows the link between biology and time. For example, I would want to have the posibility to look at the mannequin associated with each footstep (body state). I would then want to click on, for example, the hips and show d3 generated plots of the kinematics (8 line charts in total, covering displacement, velocity, acceleration and jerk of the joint and its endpoint). The mannequin at the starting line should also be able to show the body's muscle tendon mechanics( 8 line plots showing the muscle-length force, muscle-length velocity, tendon activation dynamics etc).

The app should include optimization. Currently, I can only draw static plots but I think it would be kickass if I could do that with the mannequin. That is, change things(weight or length of the limbs or radius of gyration) and  then see the associated kinematics and inverse dynamics plots from the new "mannequin" state. The actual optimisation would be done backend. 

Lastly, how do I make the canvas a div element with a div id. 
[postures.txt](https://github.com/boytchev/mannequin.js/files/10148781/postures.txt)

The link below confirms that map integration is possible

https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/

How can I make an instance of createScene()? 

`renderer.setSize( window.innerWidth * 0.3, window.innerHeight* 0.4 )
var controls = new THREE.OrbitControls(camera, renderer.domElement);`

There wont be any need to change your code. I have attached the postures that  I need rendered to an output file.

**Comment by boytchev** [comment]
Hi again –

I'm not sure I can identify the questions in your message. Anyway, here is my best attempt:

> I would want to have the posibility to look at the mannequin associated with each footstep (body state).

For this you should have a posture for each state if you want to mannequin to show each footstep

> I would then want to click on, for example, the hips

For this you can use the traditional raytracing that Three.js supports -- mannequin already uses this approach in the editor. You can see there how it is made.

> and show d3 generated plots of the kinematics

The best would be to overlay the d3 plot over the canvas

> That is, change things(weight or length of the limbs or radius of gyration) and then see the associated kinematics and inverse dynamics plots from the new "mannequin" state.

Currently size of body parts can be changed. There is no any associated mass. Also, mannequin does not do any kinematics -- it is controlled by the users. So if you want to have a figure walk and then extract some data from this, you have to make the figure walk.

>Lastly, how do I make the canvas a div element with a div id.

You cannot. 3D graphics can only be shown in a canvas. However, you can do other things that produce similar effect. The simplest is to put a transparent div over the canvas, then you can has something in the div and it will appear over the 3D graphics in the canvas. As for id, you can add an id to a canvas. This is not a problem.

> The link below confirms that map integration is possible

This is good.

> How can I make an instance of createScene()?

You do not need this. `createScene` is just to pack initialization staff, so that all examples and demos as as short as it is possible. You can use mannequin with your own Three.js scene and setup, without using `createScene` at all.

> var controls = new THREE.OrbitControls(camera, renderer.domElement);

The link with demo code of how to integrate Three.js objects with the map service can be your starting point. In that example, the 3D model is a GLTF object. My expectation is that at that point you can create any Three.js object and add it to the scene (including mannequin figure). As for `OrbitControls` -- I'd expect that you may not need it, as the map service might have its own orbiting functions. Also, the example does not show how to make per frame animations. Maybe there are some specifications that have details about this.

> There wont be any need to change your code. I have attached the postures that I need rendered to an output file.

In the worst scenario, you can generate GLTF files from these postures then add them on specific locations on your map.

– Pavel

**Comment by ksachikonye** [comment]
Hey Pavel, I tried out the GLTFExporter function and it just didnt seem to work. I then took the mannequin in the zip file you posted and managed to add the mannequin into mapbox 3D maps. I have attached a picture. So, it works, now I just need help with making the GLTFExporter work. When I import the import the module in the header, my IDE keeps telling me that the function/class does not exist. Should I be using the minimised version ?
![mannequin_in_map](https://user-images.githubusercontent.com/72452810/209693172-dd4470c7-4142-49c5-97ac-a0a9e19b4c0c.PNG)
